version: '3'
services:
  geek-frontend:
    image: frontend:latest
    restart: always
    ports:
      - 8081:80

  geek-crud-example-backend:
    image: registry.heroku.com/geek-lesson-07-spring/web:latest
    ports:
      - 8080
    restart: always


