GET localhost:8080/student/all
###

GET localhost:8080/student/1
###

POST localhost:8080/student/new
Content-Type: application/json

{
  "id" : 3,
  "name": "Kiselev22",
  "age": 29
}
###

DELETE localhost:8080/student/remove/2
###